### ISSUE TITLE
Please add OnsenUI 2 component suite and theme

### ISSUE THREAD

**Issue by cyclops24** [ShakingMap/rf-form#1]
Hi @zhaoyao91 ,
First thanks for your package. I post this issue as a feature request man. :wink: 
Please add OnsenUI 2 (https://onsen.io/v2/) component suite if you can. Then many developers can use your form generator in mobile applications.
OnsenUI 2 is one of the most strongest mobile UI framework that based on react.

Thanks man.

**Comment by zhaoyao91** [comment]
@cyclops24 thanks for attention. As you see, this project lacks usage and supports, and I'm afraid it may not be so light and flex to handle the target problem. I love it and the idea, but these days I don't have much time with it. I recommend you to see the great alternative [uniforms](https://github.com/vazco/uniforms).

In the future if I have time and requirements for such project, I will consider to split it into smaller pieces so you don't have to wait particular UI suit, and it will be more easy to maintain~

Thanks!

**Comment by cyclops24** [comment]
@zhaoyao91 Thanks for your replay So I wish best thing for you and this package man and wish see this again with more power soon. :wink:
